### ISSUE TITLE
nvim: AttributeError: NoneType object has no attribute switch

### ISSUE THREAD

**Issue by tschottdorf** [sourcegraph/sourcegraph-vim#12]
up-to-date at time of writing, neovim config https://gist.github.com/tschottdorf/7a5a08cd3332444aa2ece8ac0f7be003

A colleague of mine was able to use sourcegraph right away without any trouble, but not me. Essentially any cursor movement yields variants of

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/tschottdorf/.config/nvim/plugged/sourcegraph-vim/plugin/sourcegraph_lib.py", line 37, in run
    self.sourcegraph_instance.on_selection_modified_handler(item)
  File "/Users/tschottdorf/.config/nvim/plugged/sourcegraph-vim/plugin/sourcegraph_lib.py", line 182, in on_selection_modified_handler
    return_object = self.get_sourcegraph_request(lookup_args.filename, lookup_args.cursor_offset, lookup_args.preceding_selection, lookup_args.selected_token)
  File "/Users/tschottdorf/.config/nvim/plugged/sourcegraph-vim/plugin/sourcegraph_lib.py", line 196, in get_sourcegraph_request
    log_symbol_failure(reason=stderr)
  File "/Users/tschottdorf/.config/nvim/plugged/sourcegraph-vim/plugin/sourcegraph_lib.py", line 463, in log_symbol_failure
    log_output('Failed to find symbol. Reason: %s' % reason, is_symbol=True)
  File "/Users/tschottdorf/.config/nvim/plugged/sourcegraph-vim/plugin/sourcegraph_lib.py", line 476, in log_output
    print(output)
  File "/Users/tschottdorf/Library/Python/2.7/lib/python/site-packages/neovim/plugin/script_host.py", line 166, in write
    self.redirect_handler(data)
  File "/Users/tschottdorf/Library/Python/2.7/lib/python/site-packages/neovim/plugin/script_host.py", line 60, in <lambda>
    sys.stdout = RedirectStream(lambda data: nvim.out_write(data))
  File "/Users/tschottdorf/Library/Python/2.7/lib/python/site-packages/neovim/api/nvim.py", line 286, in out_write
    return self.request('vim_out_write', msg)
  File "/Users/tschottdorf/Library/Python/2.7/lib/python/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/tschottdorf/Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 89, in request
    v = self._yielding_request(method, args)
  File "/Users/tschottdorf/Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 154, in _yielding_request
    return parent.switch()
AttributeError: 'NoneType' object has no attribute 'switch'
```

Calling `:GRAPH` manually is a no-op - nothing happens.

**Comment by uforic** [comment]
Hey tschottdorf, thanks for reporting this, we are looking into it.

Looks like Neovim is trying to pipe the print(output) command somewhere, and it is throwing an error when output is None.

I didn't know that neovim had this behavior, I'm going to push a fix for this ASAP, will let you know when its up!

**Comment by uforic** [comment]
Hey tschottdorf,

I have a new branch if you'd like to try it out: neovim/print_error

Basically, rather than log verbose things in the Vim console, this version just logs them in our default log location: /tmp/sourcegraph-vim.log (which can be overridden). this should stop the "None" error, and the verbose information that can help us debug your setup further should be logged in that file.

Let me know if that works for you, thanks again for reporting this.

**Comment by tschottdorf** [comment]
Thanks @uforic, that makes it work. In case that's still relevant to you, [here is a gist](https://gist.github.com/tschottdorf/bbc34a755b7a14663d0e6ddf84ee4bdf) containing one `:GRAPH` invocation.
