### ISSUE TITLE
Error when opening a go file.

### ISSUE THREAD

**Issue by ianwalter** [sourcegraph/sourcegraph-vim#15]
```
Error detected while processing function LookupSymbol:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/.vim/bundle/sourcegraph-vim/plugin/sourcegraph_vi.py", line 6, in <module>
    import sourcegraph_lib
  File "/Users/me/.vim/bundle/sourcegraph-vim/plugin/sourcegraph_lib.py", line 15, in <module>
    from urllib2 import Request, urlopen
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodec
Info_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
line   19:
...
```

**Comment by uforic** [comment]
Hey, thanks for filing this.

When I search for this line: "Symbol not found: __PyCodec", I found this result on StackOverflow: 
http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder-trying-to-register-a-packa

It seems like it may be a similar issue; the user in that ticket had upgraded Python, and Python code in their IDE wasn't executing properly. Mind checking if the StackOverflow is helpful?

Separately, I'm working on a diagnostic.py file that can be run alongside the app, just to provide a better ability to debug.

**Comment by ianwalter** [comment]
@uforic Yup seems to be a problem with Python 2.7.11 from Homebrew. I uninstalled it and I'm using 2.7.10 which I think is shipped with macOS. I'm not getting that error anymore. Closing this since it's probably an issue with Homebrew. Thanks!
